config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    root to: 'toppages#index'
  
  get '/login', to: 'toppages#login'
  get 'login/creator', to: 'sessions#new'
  post 'login/creator', to: 'sessions#create'

  get 'login/editor',  to: 'sessions#editornew'
  post 'login/editor', to: 'sessions#editorcreate'
  get 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'signup_0', to: 'users#new'
  get 'profile', to: 'users#show'

  
  get 'mypage', to: 'works#show'
  get 'mypage/edit', to: 'works#edit'
  
  get 'inquiry', to: 'inquiry#index'
  

  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :works, only: [:show, :create, :edit, :destroy]

  resources :genres 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :work_genres
    has_many :works, through: :work_genres, source: :work
end

app/models/user.rb
class User < ApplicationRecord
  # include ImageUploader::Attachment(:image)
  
    # include ImageUploader[:image]
    include ImageUploader::Attachment(:image)

    before_save { self.email.downcase! }

    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_one :work
    
    accepts_nested_attributes_for :work, update_only: true
end

app/models/work.rb
class Work < ApplicationRecord
    belongs_to :user
    has_many :work_genres
    has_many :genres, through: :work_genres
    
    # accepts_nested_attributes_for :genre_ids, update_only: true

 
  def self.ransackable_attributes(auth_object = nil)
    ["assistant_history", "career",  "drawing_form", "genre", "history", "link_url", "profile", "publishdate", "publisher", "sns_url",  "working_style"]
  end
    
    
  def self.ransackable_associations(auth_object = nil)
    ["genres", "user", "work_genres"]
  end
    

end

app/models/work_genre.rb
class WorkGenre < ApplicationRecord
  belongs_to :work
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def editornew
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end
  
  def editorcreate
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = '編集者としてログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '編集者としてのログインに失敗しました。'
      render :new
    end
  end
  

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController


    def index
        if (logged_in? && params[:q] == nil)
            @pagy, @users = pagy(User.all.order("created_at desc"))
        else
            @users = nil
        end
        @q = Work.ransack(params[:q])

        if (params[:q])
            @works = @q.result.includes(:work, :profile_or_history).order(created_at: :desc)
            @users = @works.map do |work| work.user end
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 50)
  end
  
  def show
    @user = User.find(params[:id])
    
    # @user = current_user 
    #   if @user.author_flag == 1
    #   elsif @user.author_flag == 0
    #   end
  end
  
  def edit 

  end
    
    
  def new
    @user = User.new
  end 
  
  def create
    @user = User.new(user_params)
    genres = nil
    if params[:work]
       genres = params[:work][:genre_ids]
    end

    if (@user.save) 
      flash[:success] = "ユーザー登録できました。"
      #if (@user.auther_flag)
      #   redirect_to creater_home(@user)
      # else
      #   redirect_to editor_home(@user)
      # end
      
      if (genres)
        genres.map! do |genre| genre.to_i end
        genres.reject! do |i | i == 0 end
        @user.work.genre_ids = genres
      end
                  
      
      redirect_to @user
    else
      flash[:error] = "ユーザー登録できませんでした。"
      render :new
    end

  end  
  
  def update
    @user = User.find(params[:id])
    
    @genres = params[:work][:genre_ids]
    
    if (@user.update(user_params))
        flash[:success] = "ユーザー更新成功"
        
          @genres.map! do |genre| genre&.to_i end
          @genres.reject! do |i | i == 0 end
          @user.work.genre_ids = @genres
                  
        redirect_to mypage_url
    else
          flash[:error] = "ユーザー登録できませんでした。"
          render 'works/show'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :author_flag, :body, :image,
      work_attributes:[:link_url, :age, :career, :assistant_history, :drawing_form, :working_style, :genre,
       :sns_url, :profile, genres_ids:[]])
  end
  
# "work_attributes"=>{"link_url"=>"aaaaa", "age"=>"", "career"=>"ジャンプ賞", "assistant_history"=>"おだえいいちろう",
# "drawing_form"=>"デジタル", "working_style"=>"在宅", "genre"=>"", "sns_url"=>"", "profile"=>"がんばります  
  
  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :require_user_logged_in
  # before_action :correct_user, only: [:edit, :destroy]

  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 50)
  end

  def show
    @user = current_user 
    
  end

  def create
  end

  def edit
      @user = current_user 
      # @genres = @user.work&.genres&.map do |r| r.name end
      
      @genres = []
      if @user.work
        @genres = @user.work.genres.map do |r| r.name end
      end
      # @work = current_user.build_work
      # @work = Work.initialize_or_find_by(user_id: @user.id)

    # @work = current_user.works.build(work_params)
    if @user.save
      flash[:success] = 'プロフィール編集に成功しました'
      render 
    else
      @pagy, @user = pagy(current_user.works.order(id: :desc))
      flash.now[:danger] = 'プロフィール編集に失敗しました'
      render 
    end
  end

  def destroy
    @work.destroy
  end
  
  private

  # def works_params
  #   params.require(:work).permit(:email)
  # end

  # def correct_user
  #   @work = current_user.works.find_by(id: params[:id])
  #   unless @work
  #     redirect_to root_url
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
 end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/inquiry/index.html.erb
<div class="text-center">
  <h1>お問い合わせ</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'お名前' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
      </div>

      <div class="mb-3">
       <%= f.label "あなたはクリエイター or 編集者どちらで登録されてますか？" %>
        <%= f.select [['編集者',0],['クリエイター',1]], { include_blank: true, selected: 0 }, class: 'form-control' %>   
    　</div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'お問い合わせ内容' %>
      </div>
      

      <%= f.submit '上記の内容で問い合わせをする', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">AE-connect</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
  <% if logged_in? %>
    <div class="btn-group">
      <ul class="navbar-nav ">
        <li class="ms-3"><%= link_to 'マイプロフィール', mypage_path, class: 'nav-link' %></li>
        <li class="ms-3"><%= link_to 'お気に入り一覧', users_path, class: 'nav-link' %></li>
        <li class="ms-3"><%= link_to 'メール一覧', users_path, class: 'nav-link' %></li>
        <li class="ms-3"><%= link_to 'お問い合わせ', inquiry_path, class: 'nav-link' %></li>
        <li class="ms-3"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
      </ul>
    </div>
  <% else %>
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to '新規登録をする', signup_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
    </ul>
  <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>AE-connect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

  </head>
  
  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>

    <% if @users.any? %>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="offset-1 col-10">
          
          <%= search_form_for @q, url: root_url do |f| %>
            <%= f.search_field :profile_or_history_cont, placeholder: 'キーワード' %>
            <%= f.submit %>
          <% end %>
        </div>
        
        <% @users.each do |user| %>
    
          <div class="col">
            <div class="card h-100">
              <% if user.image != nil %>
                <%= image_tag user.image_url(:small), class:'card-img-top img-fluid' %>
              <% else %>
                <%= image_tag '20200501_noimage.png', class: 'card-img-top img-fluid' %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to user.name, user %></h5>
                <p class="card-text">.</p>
                <p><a class="link-opacity-100-hover" href="#"><%= @user&.work&.sns_url %></a></p>
                
                <p class="card-text">得意ジャンル</p>
                <% user.work&.genres&.each do |genre|  %>
                  <li class="list-group-item"><%= genre.name %></li>
                <% end %>
                </ul>       
              </ul>                   
                <p>作品を掲載しているURL</p>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  
      <% else %>
          該当ユーザーはいませんでした
      <% end %>

<% else %>

<div class="bg-secondary p-3 p-sm-5 my-4 rounded">
  <div class="text-center text-white">
    <h1>AE-connect</h1>
        <%= link_to '新規登録をする', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

<%= link_to "新規登録をする", new_user_path, class:'btn btn-primary' %>

<% end %>

app/views/toppages/login.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
<div class="d-flex justify-content-around mb-3 p-sm-5 my-4 rounded">
    <div class="p-2 w-100 text-center text-white">
        <%= link_to 'AE-connectにクリエイターとしてログインする', login_creator_path, class: 'btn btn-lg btn-primary' %>
  </div>
  
    <div class="p-2 w-100 text-center text-white">
        <%= link_to 'AE-connectに編集者としてログインする',login_editor_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="mb-3 d-flex">

<!--以下のコードは後半で編集をかける-->
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'プロフィール', user_path(user), class: "text-decoration-none" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィール編集ページ</h1>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録ページ</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, '再パスワード入力' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :author_flag, "あなたはクリエイター or 編集者どちらで登録されますか？" %>
        <%= f.select :author_flag, [['編集者',0],['クリエイター',1]], { include_blank: true, selected: 0 }, class: 'form-control' %>
      </div>

      <%= f.submit '上記の内容で登録する', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <div class="list-group">
      <ul class="list-group list-group-horizontal">
        
        <li class="list-group-item">お名前（ペンネーム）</li>
        <li class="list-group-item"><%= @user.name %></li>
       </ul>

      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">連絡先メールアドレス</li>
        <li class="list-group-item"><%= @user.email %></li>
      </ul>
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">作品を掲載しているURL</li>
        <li class="list-group-item"><%= @user.work&.link_url %></li>

      </ul>
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">年齢</li>
        <li class="list-group-item"><%= @user.work&.age %></li>
      </ul>
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">経歴（受賞歴）</li>
        <li class="list-group-item"><%= @user.work&.career %></li>
      </ul>      
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">アシスタント歴（ある場合）</li>
        <li class="list-group-item"><%= @user.work&.assistant_history %></li>
      </ul>      
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">可能な作画形式</li>
        <li class="list-group-item"><%= @user.work&.drawing_form %></li>
      </ul>   
      
     <ul class="list-group list-group-horizontal">
        <li class="list-group-item">使用できるアイテム</li>
        <li class="list-group-item"><%= @user.work&.drawing_form %></li>
        <li class="list-group-item"></li>
      </ul>    
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">可能な勤務形態（在宅・通い・泊まり）</li>
        <li class="list-group-item"><%= @user.work&.working_style %></li>
      </ul>   
      
      <ul class="list-group list-group-horizontal">
      <% genres = (temp = @user.work&.genres&.pluck(:name)) ? temp : [] %>

        <li class="list-group-item">得意ジャンル</li>
          <ul class="list-group m-1">
            <% genres.each do |genre| %>
          <li class="list-group-item"><%= genre %></li>
        <% end %>
        </ul>       
      </ul>         
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">SNS</li>
        <li class="list-group-item"><%= @user.work&.sns_url %></li>
      </ul>         
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">プロフィール画像</li>
        <li class="list-group-item">
                    <%if @user.image_data.present? %>
            <%= image_tag @user.image_url(:small) %>
          <% end %>
        </li>
      </ul>   
      
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item">PR欄（100文字以内で表示）</li>
        <textarea class="form-control" rows="3" disabled><%= @user.work&.profile %></textarea>
      </ul>
      
      </div>
    </div>
      
<%= link_to "編集する", mypage_edit_path, class:'btn btn-primary' %>


  </div>
</div>
  

app/views/works/edit.html.erb
<div class="text-center">
  <h1>プロフィール編集画面</h1>
</div>

<div class="row m-5">
  <div class="col-md-10 offset-md-1 ">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

    <div class="row">
      <div class="col-6">
        <div class="mb-3">
          <%= f.label :name, 'お名前(ペンネーム)' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= f.label :email, 'メール' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      
        <div class="mb-3 field">
          <%= f.label :image_data, 'アバター画像' %>
          <%= f.hidden_field :image, value: current_user.cached_image_data %>
          <%= f.file_field :image %>
        </div>  
  
        <%= f.fields_for :work, @user.work || Work.new do |fw| %>
        
        <div class="mb-3">
          <%= fw.label :link_url, "作品を掲載しているURL" %>
          <%= fw.text_field :link_url, class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= fw.label :age, "年齢(非公開も可)" %>
          <%= fw.text_field :age, class: 'form-control' %>
        </div>   
        
        <div class="mb-3">
          <%= fw.label :career, "経歴（受賞歴）" %>
          <%= fw.text_field :career, class: 'form-control' %>
        </div>   
        
        <div class="mb-3">
          <%= fw.label :assistant_history, "アシスタント歴があるか" %>
          <%= fw.text_field :assistant_history, class: 'form-control' %>
        </div>   
        
        <div class="mb-3">
          <%= fw.label :drawing_forml, "可能な作画形態（デジタル・アナログ）" %>
          <%= fw.text_field :drawing_form, class: 'form-control' %>
        </div>   
        
        <div class="mb-3">
          <%= fw.label :working_stylel, "可能な勤務形式(在宅・通い・泊まり)" %>
          <%= fw.text_field :working_style, class: 'form-control' %>
        </div>    
        
      </div> <!-- 左側 -->
      
      <div class="col-6">
          <div class="mb-3">
            <%= fw.label :genre_ids, "ジャンル" %><br>
            <%= collection_check_boxes(:work, :genre_ids, Genre.all, :id, :name) do |genre| %>
              <%= genre.label do %>
                <%= genre.check_box checked: @genres.include?(genre.text) %> <!-- checkedがtrueならcheck  -->
                <%= genre.text %>
              <% end %>
            <% end %>
        　</div>

        
        <div class="mb-3">
          <%= fw.label :sns_url, 'SNS' %>
          <%= fw.text_field :sns_url, class: 'form-control' %>
          <%= fw.text_field :sns_url, class: 'form-control' %>
          <%= fw.text_field :sns_url, class: 'form-control' %>
        </div>
                
        
        <div class="mb-3">
          <%= fw.label :profile, ' PR欄（100文字以内で表示）' %>
          <%= fw.text_area :profile, class: 'form-control' ,style: "width:100%", rows: "10" %>
        </div>              
      </div>
    </div>
      <%= f.submit 'プロフィールを更新する', class: 'btn btn-primary w-100' %>
        <% end %> <!-- f.fields_for -->
    <% end %>
  </div>
</div>

app/views/works/show.html.erb
<div class="row m-3">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <!--<img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">-->
        
        <p>
          <strong>プロフィール画像</strong>
          <%if @user.image_data.present? %>
            <%= image_tag @user.image_url(:small) %>
          <% end %>
        </p>      
      
      
      </div>
    </div>
  </aside>
  <div class="col-sm-8 ">
    <div class="list-group m-3">

      <p>お名前（ペンネーム）</p>   
      <ul class="list-group m-1">
        <li class="list-group-item"><%= @user.name %></li>
       </ul>

      <p>連絡先メールアドレス</p>
      <ul class="list-group m-1">
        <li class="list-group-item"><%= @user.email %></li>
      </ul>

      <p>作品を掲載しているURL</p>
      <ul class="list-group m-1">
        <li class="list-group-item "><%= @user.work&.link_url %></li>
      </ul>
      
      <ul class="list-group m-1">
      <p>年齢</p>
        <li class="list-group-item"><%= @user.work&.age %></li>
      </ul>
      
      <ul class="list-group m-1">
      <p>経歴（受賞歴）</p>
        <li class="list-group-item"><%= @user.work&.career %></li>
      </ul>      
      
      <ul class="list-group m-1">
      <p>アシスタント歴（ある場合）</p>
        <li class="list-group-item"><%= @user.work&.assistant_history %></li>
        <li class="list-group-item w-100"></li>
      </ul>      
      
      <ul class="list-group m-1">
      <p>可能な作画形式</p>
        <li class="list-group-item"><%= @user.work&.drawing_form %></li>
        <li class="list-group-item w-100"></li>
      </ul>   
      
      <ul class="list-group m-1">
      <p>使用できるアイテム</p>
        <li class="list-group-item"><%= @user.work&.drawing_form %></li>
        <li class="list-group-item w-100"></li>
      </ul>        
      
      <ul class="list-group m-1">
      <p>可能な勤務形態（在宅・通い・泊まり）</p>
        <li class="list-group-item"><%= @user.work&.working_style %></li>
        <li class="list-group-item w-100"></li>
      </ul>   

      <p>得意ジャンル</p>
      <% genres = @user.work&.genres&.pluck(:name) %>
      <ul class="list-group m-1">
        <% genres&.each do |genre| %>
          <li class="list-group-item"><%= genre %></li>
        <% end %>
      </ul> 
      
      <ul class="list-group m-1">
      <p>SNS</p>
        <li class="list-group-item"><%= @user.work&.sns_url %></li>

      </ul>         

      
      <p>PR欄（100文字以内で表示）</p>
        <textarea class="form-control" rows="3" disabled><%= @user.work&.profile %></textarea>
      </div>
    </div>
      
<%= link_to "編集する", mypage_edit_path, class:'btn btn-primary m-3' %>


  </div>
</div>
  